WebsiteTrangSuc/WebsiteTrangSuc/Models/Sanpham.cs
namespace WebsiteTrangSuc.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    [Table("Sanpham")]
    public partial class Sanpham
    {
        public int id { get; set; }
        [Display( Name="Mã sản phẩm")]
        [StringLength(30)]
        public string MaSanPham { get; set; }
        [Display(Name="ID Loại sản phẩm")]
        public int IdLoai { get; set; }
        [Display(Name ="Tên sản phẩm")]
        [StringLength(256)]
        public string Ten { get; set; }
        [Display(Name ="Model")]
        [StringLength(30)]
        public string Model { get; set; }
        [Display(Name ="Mô tả ngắn")]
        [StringLength(300)]
        public string MotaNgan { get; set; }
        [Display(Name ="Mô tả chi tiết")]
        [Column(TypeName = "ntext")]
        public string MotaChiTiet { get; set; }
        [Display(Name ="Thông số kỹ thuật")]
        [Column(TypeName = "ntext")]
        public string TSKyThuat { get; set; }
        [Display(Name ="Từ khóa")]
        [StringLength(300)]
        public string Tukhoa { get; set; }
        [Display(Name ="ID Hãng")]
        public int? IdHang { get; set; }
        [Display(Name ="Ngày nhập")]
        [Column(TypeName = "date")]
        public DateTime? NgayNhap { get; set; }
        [Display(Name ="Ngày cập nhập cuối")]
        [Column(TypeName = "date")]
        public DateTime? NgayCapNhatCuoi { get; set; }
        [Display(Name ="Giá cũ")]
        public double? GiaCu { get; set; }
        [Display(Name ="Giá mới")]
        public double? GiaMoi { get; set; }
        [Display(Name = "Ưu tiên")]
        public short? Uutien { get; set; }
        [Display(Name = "Thực thi")]
        public int? ThucThi { get; set; }
        [Display(Name = "Hình ảnh")]
        [StringLength(300)]
        public string HinhAnh { get; set; }
        [Display(Name = "Hình ảnh 1")]
        [StringLength(300)]
        public string HinhAnh1 { get; set; }
        [Display(Name = "Hình ảnh 2")]
        [StringLength(300)]
        public string HinhAnh3 { get; set; }
        [Display(Name = "Hình ảnh 3")]
        [StringLength(300)]
        public string HinhAnh4 { get; set; }
        [Display(Name = "Tiêu biểu")]
        public bool? TieuBieu { get; set; }
        [Display(Name = "Ngôn ngữ")]
        [StringLength(20)]
        public string Ngonngu { get; set; }

        public virtual LoaiSanPham LoaiSanPham { get; set; }
    }
}

WebsiteTrangSuc/WebsiteTrangSuc/Areas/Administrator/Controllers/SanphamsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebsiteTrangSuc.Models;

namespace WebsiteTrangSuc.Areas.Administrator.Controllers
{
    public class SanphamsController : Controller
    {
        private QLBH db = new QLBH();

        // GET: Administrator/Sanphams
        public ActionResult Index()
        {
            var sanphams = db.Sanphams.Include(s => s.LoaiSanPham);
            return View(sanphams.ToList());
        }

        // GET: Administrator/Sanphams/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Sanpham sanpham = db.Sanphams.Find(id);
            if (sanpham == null)
            {
                return HttpNotFound();
            }
            return View(sanpham);
        }

        // GET: Administrator/Sanphams/Create
        public ActionResult Create()
        {
            ViewBag.IdLoai = new SelectList(db.LoaiSanPhams, "IdLoai", "Ten");
            return View();
        }

        // POST: Administrator/Sanphams/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Create([Bind(Include = "id,MaSanPham,IdLoai,Ten,Model,MotaNgan,MotaChiTiet,TSKyThuat,Tukhoa,IdHang,NgayNhap,NgayCapNhatCuoi,GiaCu,GiaMoi,Uutien,ThucThi,HinhAnh,HinhAnh1,HinhAnh3,HinhAnh4,TieuBieu,Ngonngu")] Sanpham sanpham)
        {
            if (ModelState.IsValid)
            {
                db.Sanphams.Add(sanpham);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.IdLoai = new SelectList(db.LoaiSanPhams, "IdLoai", "Ten", sanpham.IdLoai);
            return View(sanpham);
        }

        // GET: Administrator/Sanphams/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Sanpham sanpham = db.Sanphams.Find(id);
            if (sanpham == null)
            {
                return HttpNotFound();
            }
            ViewBag.IdLoai = new SelectList(db.LoaiSanPhams, "IdLoai", "Ten", sanpham.IdLoai);
            return View(sanpham);
        }

        // POST: Administrator/Sanphams/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Edit([Bind(Include = "id,MaSanPham,IdLoai,Ten,Model,MotaNgan,MotaChiTiet,TSKyThuat,Tukhoa,IdHang,NgayNhap,NgayCapNhatCuoi,GiaCu,GiaMoi,Uutien,ThucThi,HinhAnh,HinhAnh1,HinhAnh3,HinhAnh4,TieuBieu,Ngonngu")] Sanpham sanpham)
        {
            if (ModelState.IsValid)
            {
                db.Entry(sanpham).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.IdLoai = new SelectList(db.LoaiSanPhams, "IdLoai", "Ten", sanpham.IdLoai);
            return View(sanpham);
        }
        [HttpPost]
        // GET: Administrator/Sanphams/Delete/5
        public ActionResult Delete(int [] id)
        {
            foreach(var i in id)
            {
                Sanpham sp = db.Sanphams.Find(i);

                db.Sanphams.Remove(sp);
                db.SaveChanges();
            }
            return RedirectToAction("Index");

            
                //if (id == null)
            //{
            //    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            //}
            //Sanpham sanpham = db.Sanphams.Find(id);
            //if (sanpham == null)
            //{
            //    return HttpNotFound();
            //}
            //return View(sanpham);
        }

        // POST: Administrator/Sanphams/Delete/5
        //[HttpPost, ActionName("Delete")]
        //[ValidateAntiForgeryToken]
        //public ActionResult DeleteConfirmed(int id)
        //{
        //    Sanpham sanpham = db.Sanphams.Find(id);
        //    db.Sanphams.Remove(sanpham);
        //    db.SaveChanges();
        //    return RedirectToAction("Index");
        //}

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
        public ActionResult Close()
        {
            return RedirectToAction("Index", "Default");
        }
    }
}

WebsiteTrangSuc/WebsiteTrangSuc/Controllers/SanPhamController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebsiteTrangSuc.Models;

namespace WebsiteTrangSuc.Controllers
{
    public class SanPhamController : Controller
    {
        QLBH db = new QLBH();
        // GET: SanPham
        public ActionResult Index()
        {
            return View();
        }
        public PartialViewResult SanPhamMoi()
        {
            var ds = db.Sanphams.OrderByDescending(s=>s.id).ToList().Take(3);
            return PartialView(ds);
        }
        public PartialViewResult SanPhamTieuBieu()
        {
            var ds = db.Sanphams.Where(s => s.TieuBieu == true).ToList().Take(2);
            return PartialView(ds);
        }
        [HttpGet]
        public ActionResult DanhMucSP(int id  )
        {
            var dssp = db.Sanphams.Where(s => s.IdLoai == id).OrderBy(s=>s.GiaMoi).ToList();
            ViewBag.tenloai = db.LoaiSanPhams.Where(s => s.IdLoai == id).ToList().FirstOrDefault();
            return View(dssp);
        }
        [HttpGet]
        public ActionResult Chitietsanpham(int id)
        {
            var chitiet = db.Sanphams.Where(s => s.id == id).ToList().FirstOrDefault();
            var splq = db.Sanphams.Where(s => s.IdLoai == chitiet.IdLoai && s.id != chitiet.id).ToList().Take(3);
            ViewBag.sqlq = splq;
            return View(chitiet);
        }
    }
}

WebsiteTrangSuc/WebsiteTrangSuc/Areas/Administrator/Views/Sanphams/Create.cshtml
@model WebsiteTrangSuc.Models.Sanpham

@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/Administrator/Views/Shared/Admin_Layout.cshtml";
}
<script>
    $(function () {
        $("#NgayNhap").datepicker();
    });
    $(function () {
        $("#NgayCapNhatCuoi").datepicker();
    });
</script>

<h2>Thêm sản phẩm mới</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.MaSanPham, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MaSanPham, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MaSanPham, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IdLoai, "IdLoai", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("IdLoai", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.IdLoai, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Ten, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Ten, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Ten, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Model, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Model, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Model, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MotaNgan, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.MotaNgan, new { @class = "form-control" } )
                @Html.ValidationMessageFor(model => model.MotaNgan, "", new { @class = "text-danger" })
            </div>
            <script type="text/javascript">
                CKEDITOR.replace("MotaNgan");
            </script>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MotaChiTiet, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.MotaChiTiet, new { @class = "form-control" } )
                @Html.ValidationMessageFor(model => model.MotaChiTiet, "", new { @class = "text-danger" })
            </div>
            <script type="text/javascript">
                CKEDITOR.replace("MotaChiTiet");
            </script>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TSKyThuat, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.TSKyThuat,  new { @class = "form-control" } )
                @Html.ValidationMessageFor(model => model.TSKyThuat, "", new { @class = "text-danger" })
            </div>
            <script type="text/javascript">
                CKEDITOR.replace("TSKyThuat");
            </script>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Tukhoa, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Tukhoa, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Tukhoa, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IdHang, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.IdHang, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.IdHang, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NgayNhap, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NgayNhap, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NgayNhap, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NgayCapNhatCuoi, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NgayCapNhatCuoi, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NgayCapNhatCuoi, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.GiaCu, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.GiaCu, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.GiaCu, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.GiaMoi, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.GiaMoi, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.GiaMoi, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Uutien, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Uutien, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Uutien, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ThucThi, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ThucThi, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ThucThi, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.HinhAnh, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-6">
                @Html.TextBoxFor(model => model.HinhAnh, new { @class = "form-control" } )
                @Html.ValidationMessageFor(model => model.HinhAnh, "", new { @class = "text-danger" })
            </div>
            <div class="col-md-1">
                <input type="button" id="browse" value="Chọn file" class="btn btn-default" />
            </div>
            <script>
                $("#browse").click(function () {
                    var finder = new CKFinder();
                    finder.selectActionFunction = function (fileUrl) {
                        // fileUrl = fileUrl.substring(fileUrl.lastIndexOf("/") + 1);
                        $("#HinhAnh").val(fileUrl);
                    }
                    finder.popup();
                });

            </script>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.HinhAnh1, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-6">
                @Html.TextBoxFor(model => model.HinhAnh1, new { @class = "form-control" } )
                @Html.ValidationMessageFor(model => model.HinhAnh1, "", new { @class = "text-danger" })
            </div>
            <div class="col-md-1">
                <input type="button" id="browse1" value="Chọn file" class="btn btn-default" />
            </div>
            <script>
                $("#browse1").click(function () {
                    var finder = new CKFinder();
                    finder.selectActionFunction = function (fileUrl) {
                        // fileUrl = fileUrl.substring(fileUrl.lastIndexOf("/") + 1);
                        $("#HinhAnh1").val(fileUrl);
                    }
                    finder.popup();
                });

            </script>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.HinhAnh3, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-6">
                @Html.TextBoxFor(model => model.HinhAnh3, new { @class = "form-control" } )
                @Html.ValidationMessageFor(model => model.HinhAnh3, "", new { @class = "text-danger" })
            </div>
            <div class="col-md-1">
                <input type="button" id="browse3" value="Chọn file" class="btn btn-default" />
            </div>
            <script>
                $("#browse3").click(function () {
                    var finder = new CKFinder();
                    finder.selectActionFunction = function (fileUrl) {
                        // fileUrl = fileUrl.substring(fileUrl.lastIndexOf("/") + 1);
                        $("#HinhAnh3").val(fileUrl);
                    }
                    finder.popup();
                });

            </script>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.HinhAnh4, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-6">
                @Html.TextBoxFor(model => model.HinhAnh4, new { @class = "form-control"})
                @Html.ValidationMessageFor(model => model.HinhAnh4, "", new { @class = "text-danger" })
            </div>
            <div class="col-md-1">
                <input type="button" id="browse4" value="Chọn file" class="btn btn-default" />
            </div>
            <script>
                $("#browse4").click(function () {
                    var finder = new CKFinder();
                    finder.selectActionFunction = function (fileUrl) {
                        // fileUrl = fileUrl.substring(fileUrl.lastIndexOf("/") + 1);
                        $("#HinhAnh4").val(fileUrl);
                    }
                    finder.popup();
                });

            </script>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TieuBieu, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.TieuBieu)
                    @Html.ValidationMessageFor(model => model.TieuBieu, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Ngonngu, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.Ngonngu, new List<SelectListItem>
          {
              new SelectListItem() {Text="Tiếng Việt", Value="vi-VN" },
              new SelectListItem() {Text="Tiếng Anh", Value="en-US" }
          }, new { @class = "form-control" })
                @*@Html.EditorFor(model => model.Ngonngu, new { htmlAttributes = new { @class = "form-control" } })*@
                @*@Html.ValidationMessageFor(model => model.Ngonngu, "", new { @class = "text-danger" })*@
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Trở lại", "Index")
</div>

WebsiteTrangSuc/WebsiteTrangSuc/Areas/Administrator/Views/Sanphams/Index.cshtml
@model IEnumerable<WebsiteTrangSuc.Models.Sanpham>

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Administrator/Views/Shared/Admin_Layout.cshtml";
}
<script>
    $(function () {
        $(".popup_button_delete").click(function (e) {
            e.preventDefault();
            bootbox.dialog({
                message: "Bạn có chắc chắn muốn xóa các thông tin đã chọn không?",
                title: "Xác nhận xóa thông tin",
                buttons: {
                    success: {
                        label: "Đồng ý",
                        className: "btn-success",
                        callback: function () {
                            $('form').submit();
                            //__doPostBack('btnDelete', 'OnClick');
                        }
                    },
                    danger: {
                        label: "Quay lại",
                        className: "btn-danger",
                        callback: function () {
                            //Example.show("Xem lại");
                        }
                    }
                }
            });
            return false;
        });
    });
</script>
@using (Html.BeginForm("Delete", "Sanphams", FormMethod.Post))
{
    <h1></h1>
    <div class="panel panel-default container MaginTop">

        <div class="panel-heading">
            <h3 class="panel-title">
                Quản lý sản phẩm
                <div class="btn-group" role="group" aria-label="..." style="float:right">
                    @Html.ActionLink("Thêm mới", "Create", "Sanphams", new { @class = "btn btn-default" })
                    <input type="submit" value="Xóa" , class="btn btn-default popup_button_delete" />
                    @*@Html.ActionLink("Xóa", "Delete", "LoaiSanPham", new { @class = "btn btn-default" })*@
                    @Html.ActionLink("Thoát", "Close", "Sanphams", new { @class = "btn btn-default" })
                </div>
            </h3>
        </div>
        <div class="panel-body">
            <table class="table">
                <tr>
                    <th>Chọn</th>
                    <th>STT</th>
                    <th>
                        @Html.DisplayNameFor(model => model.LoaiSanPham.Ten)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.MaSanPham)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Ten)
                    </th>
                    @*<th>
                            @Html.DisplayNameFor(model => model.Model)
                        </th>*@
                    @*<th>
                            @Html.DisplayNameFor(model => model.MotaNgan)
                        </th>*@
                    <th>
                        @Html.DisplayNameFor(model => model.MotaChiTiet)
                    </th>
                    @*<th>
                            @Html.DisplayNameFor(model => model.TSKyThuat)
                        </th>*@
                    <th>
                        @Html.DisplayNameFor(model => model.Tukhoa)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.IdHang)
                    </th>
                    @*<th>
                            @Html.DisplayNameFor(model => model.NgayNhap)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.NgayCapNhatCuoi)
                        </th>*@
                    <th>
                        @Html.DisplayNameFor(model => model.GiaCu)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.GiaMoi)
                    </th>
                    @*<th>
                            @Html.DisplayNameFor(model => model.Uutien)
                        </th>*@
                    <th>
                        @Html.DisplayNameFor(model => model.ThucThi)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.HinhAnh)
                    </th>
                    @*<th>
                            @Html.DisplayNameFor(model => model.HinhAnh1)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.HinhAnh3)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.HinhAnh4)
                        </th>*@
                    <th>
                        @Html.DisplayNameFor(model => model.TieuBieu)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Ngonngu)
                    </th>
                    <th></th>
                </tr>
                @{
                    var i = 1;

                    foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                <input type="checkbox" name="id" id="id" value="@item.id" />
                            </td>
                            <td>@i</td>
                            <td>
                                @*@Html.DisplayFor(modelItem => item.LoaiSanPham.Ten)*@
                                @Html.ActionLink(item.Ten, "Edit", new { id = item.id })
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.MaSanPham)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Ten)
                            </td>
                            @*<td>
                                    @Html.DisplayFor(modelItem => item.Model)
                                </td>*@
                            @*<td>
                                    @Html.DisplayFor(modelItem => item.MotaNgan)
                                </td>*@
                            <td>
                                @Html.DisplayFor(modelItem => item.MotaChiTiet)
                            </td>
                            @*<td>
                                    @Html.DisplayFor(modelItem => item.TSKyThuat)
                                </td>*@
                            <td>
                                @Html.DisplayFor(modelItem => item.Tukhoa)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.IdHang)
                            </td>
                            @*<td>
                                    @Html.DisplayFor(modelItem => item.NgayNhap)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.NgayCapNhatCuoi)
                                </td>*@
                            <td>
                                @Html.DisplayFor(modelItem => item.GiaCu)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.GiaMoi)
                            </td>
                            @*<td>
                                    @Html.DisplayFor(modelItem => item.Uutien)
                                </td>*@
                            <td>
                                @Html.DisplayFor(modelItem => item.ThucThi)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.HinhAnh)
                            </td>
                            @*<td>
                                    @Html.DisplayFor(modelItem => item.HinhAnh1)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.HinhAnh3)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.HinhAnh4)
                                </td>*@
                            <td>
                                @Html.DisplayFor(modelItem => item.TieuBieu)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Ngonngu)
                            </td>

                        </tr>
                        i++;
                    }
                }
            </table>
        </div>

    </div>

 }