WebsiteTrangSuc/WebsiteTrangSuc/Models/LoaiSanPham.cs
namespace WebsiteTrangSuc.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    [Table("LoaiSanPham")]
    public partial class LoaiSanPham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LoaiSanPham()
        {
            Sanphams = new HashSet<Sanpham>();
        }

        [Key]
        [Display (Name ="Mã loại")]
        public int IdLoai { get; set; }

        [StringLength(256)]
        [Display(Name = "Tên loại")]
        public string Ten { get; set; }
        [Display(Name = "Tiêu đề")]
        [StringLength(300)]
        public string Tieude { get; set; }
        [Display(Name = "Mô tả")]
        [Column(TypeName = "ntext")]
        public string Mota { get; set; }
        [Display(Name = "Ưu tiên")]
        public short? Uutien { get; set; }
        [Display(Name = "Hình ảnh")]
        [StringLength(256)]
        public string Hinhanh { get; set; }
        [Display(Name = "Từ khóa")]
        [StringLength(300)]
        public string Tukhoa { get; set; }
        [Display(Name = "Thực thi")]
        public int? Thucthi { get; set; }
        [Display(Name = "Vị trí")]
        public int? Vitri { get; set; }
        [Display(Name = "Ngôn ngữ")]
        [StringLength(5)]
        public string Ngonngu { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sanpham> Sanphams { get; set; }
    }
}

WebsiteTrangSuc/WebsiteTrangSuc/Areas/Administrator/Controllers/LoaiSanPhamsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebsiteTrangSuc.Models;

namespace WebsiteTrangSuc.Areas.Administrator.Controllers
{
    public class LoaiSanPhamsController : Controller
    {
        private QLBH db = new QLBH();

        // GET: Administrator/LoaiSanPhams
        public ActionResult Index()
        {
            return View(db.LoaiSanPhams.ToList());
        }

        // GET: Administrator/LoaiSanPhams/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            LoaiSanPham loaiSanPham = db.LoaiSanPhams.Find(id);
            if (loaiSanPham == null)
            {
                return HttpNotFound();
            }
            return View(loaiSanPham);
        }

        // GET: Administrator/LoaiSanPhams/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Administrator/LoaiSanPhams/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Create([Bind(Include = "IdLoai,Ten,Tieude,Mota,Uutien,Hinhanh,Tukhoa,Thucthi,Vitri,Ngonngu")] LoaiSanPham loaiSanPham)
        {
            if (ModelState.IsValid)
            {
                db.LoaiSanPhams.Add(loaiSanPham);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(loaiSanPham);
        }

        // GET: Administrator/LoaiSanPhams/Edit/5
     
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            LoaiSanPham loaiSanPham = db.LoaiSanPhams.Find(id);
            if (loaiSanPham == null)
            {
                return HttpNotFound();
            }
            return View(loaiSanPham);
        }

        // POST: Administrator/LoaiSanPhams/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Edit([Bind(Include = "IdLoai,Ten,Tieude,Mota,Uutien,Hinhanh,Tukhoa,Thucthi,Vitri,Ngonngu")] LoaiSanPham loaiSanPham)
        {
            if (ModelState.IsValid)
            {
                db.Entry(loaiSanPham).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(loaiSanPham);
        }
        [HttpPost]
        // GET: Administrator/LoaiSanPhams/Delete/5
        public ActionResult Delete(int[] idLoai)
        {
            foreach(var i in idLoai)
            {
                LoaiSanPham lsp = db.LoaiSanPhams.Find(i);
                var dssp = db.Sanphams.Where(s => s.IdLoai == i).ToList();
                if (dssp.Count>0)
                {
                    foreach (var sp in dssp)
                    db.Sanphams.Remove(sp);
                    db.SaveChanges();
                }
                db.LoaiSanPhams.Remove(lsp);
                db.SaveChanges();
            }
            return RedirectToAction("Index");
            //if (id == null)
            //{
            //    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            //}
            //LoaiSanPham loaiSanPham = db.LoaiSanPhams.Find(id);
            //if (loaiSanPham == null)
            //{
            //    return HttpNotFound();
            //}
            //return View(loaiSanPham);
        }
        

        // POST: Administrator/LoaiSanPhams/Delete/5
        //[HttpPost, ActionName("Delete")]
        //[ValidateAntiForgeryToken]
        //public ActionResult DeleteConfirmed(int id)
        //{
        //    LoaiSanPham loaiSanPham = db.LoaiSanPhams.Find(id);
        //    db.LoaiSanPhams.Remove(loaiSanPham);
        //    db.SaveChanges();
        //    return RedirectToAction("Index");
        //}

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
        public ActionResult Close()
        {

            return RedirectToAction("Index","Default");
        }
    }
}

WebsiteTrangSuc/WebsiteTrangSuc/Areas/Administrator/Views/LoaiSanPhams/Create.cshtml
@model WebsiteTrangSuc.Models.LoaiSanPham

@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/Administrator/Views/Shared/Admin_Layout.cshtml";
}



@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Thêm mới loại sản phẩm</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Ten, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Ten, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Ten, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Tieude, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Tieude, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Tieude, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">

            @Html.LabelFor(model => model.Mota, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Mota, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Mota, "", new { @class = "text-danger" })

            </div>
            <script type="text/javascript">
                CKEDITOR.replace("Mota");
            </script>

        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Uutien, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Uutien, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Uutien, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Hinhanh, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-6">
                @Html.TextBoxFor(model => model.Hinhanh, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Hinhanh, "", new { @class = "text-danger" })
            </div>
            <div class="col-md-1">
                <input type="button" id="browse" value="Chọn file" class="btn btn-default" />
            </div>
            <script>
                $("#browse").click(function () {
                    var finder = new CKFinder();
                    finder.selectActionFunction = function (fileUrl) {
                        // fileUrl = fileUrl.substring(fileUrl.lastIndexOf("/") + 1);
                        $("#Hinhanh").val(fileUrl);
                    }
                    finder.popup();
                });

            </script>
        </div>


        <div class="form-group">
            @Html.LabelFor(model => model.Tukhoa, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Tukhoa, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Tukhoa, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Thucthi, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Thucthi, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Thucthi, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Vitri, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Vitri, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Vitri, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Ngonngu, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @*@Html.EditorFor(model => model.Ngonngu, new { htmlAttributes = new { @class = "form-control" } })*@
                <select name="Ngonngu" class="form-control">
                    <option value="vi-VN">Tiếng việt</option>
                    <option value="en-US">Tiếng anh</option>
                </select>
                @Html.ValidationMessageFor(model => model.Ngonngu, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Thêm mới" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Trở lại", "Index")
</div>

WebsiteTrangSuc/WebsiteTrangSuc/Areas/Administrator/Views/LoaiSanPhams/Delete.cshtml
@model WebsiteTrangSuc.Models.LoaiSanPham

@{
    ViewBag.Title = "Delete";
    Layout = "~/Areas/Administrator/Views/Shared/Admin_Layout.cshtml";
}



<h3>Are you sure you want to delete this?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Ten)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Ten)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Tieude)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Tieude)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Mota)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Mota)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Uutien)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Uutien)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Hinhanh)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Hinhanh)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Tukhoa)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Tukhoa)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Thucthi)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Thucthi)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Vitri)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Vitri)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Ngonngu)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Ngonngu)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

WebsiteTrangSuc/WebsiteTrangSuc/Areas/Administrator/Views/LoaiSanPhams/Details.cshtml
@model WebsiteTrangSuc.Models.LoaiSanPham

@{
    ViewBag.Title = "Details";
    Layout = "~/Areas/Administrator/Views/Shared/Admin_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>LoaiSanPham</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Ten)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Ten)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Tieude)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Tieude)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Mota)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Mota)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Uutien)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Uutien)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Hinhanh)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Hinhanh)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Tukhoa)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Tukhoa)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Thucthi)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Thucthi)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Vitri)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Vitri)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Ngonngu)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Ngonngu)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.IdLoai }) |
    @Html.ActionLink("Back to List", "Index")
</p>

WebsiteTrangSuc/WebsiteTrangSuc/Areas/Administrator/Views/LoaiSanPhams/Edit.cshtml
@model WebsiteTrangSuc.Models.LoaiSanPham

@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Administrator/Views/Shared/Admin_Layout.cshtml";
}



@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Sửa loại sản phẩm</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.IdLoai)

        <div class="form-group">
            @Html.LabelFor(model => model.Ten, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Ten, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Ten, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Tieude, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Tieude, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Tieude, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Mota, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Mota, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Mota, "", new { @class = "text-danger" })
            </div>
            <script type="text/javascript">
                CKEDITOR.replace("Mota");
            </script>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Uutien, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Uutien, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Uutien, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Hinhanh, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-6">
                @Html.TextBoxFor(model => model.Hinhanh, new { @class = "form-control" } )
                @Html.ValidationMessageFor(model => model.Hinhanh, "", new { @class = "text-danger" })
            </div>
            <div class="col-md-1">
                <input type="button" id="browse" value="Chọn file" class="btn btn-default" />
            </div>
            <script>
                $("#browse").click(function () {
                    var finder = new CKFinder();
                    finder.selectActionFunction = function (fileUrl) {
                        // fileUrl = fileUrl.substring(fileUrl.lastIndexOf("/") + 1);
                        $("#Hinhanh").val(fileUrl);
                    }
                    finder.popup();
                });

            </script>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Tukhoa, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Tukhoa, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Tukhoa, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Thucthi, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Thucthi, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Thucthi, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Vitri, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Vitri, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Vitri, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Ngonngu, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Ngonngu, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Ngonngu, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Lưu" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Trở lại", "Index")
</div>

WebsiteTrangSuc/WebsiteTrangSuc/Areas/Administrator/Views/LoaiSanPhams/Index.cshtml
@model IEnumerable<WebsiteTrangSuc.Models.LoaiSanPham>

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Administrator/Views/Shared/Admin_Layout.cshtml";
}
<script>
    $(function () {
        $(".popup_button_delete").click(function (e) {
            e.preventDefault();
            bootbox.dialog({
                message: "Bạn có chắc chắn muốn xóa các thông tin đã chọn không?",
                title: "Xác nhận xóa thông tin",
                buttons: {
                    success: {
                        label: "Đồng ý",
                        className: "btn-success",
                        callback: function () {
                            $('form').submit();
                            //__doPostBack('btnDelete', 'OnClick');
                        }
                    },
                    danger: {
                        label: "Quay lại",
                        className: "btn-danger",
                        callback: function () {
                            //Example.show("Xem lại");
                        }
                    }
                }
            });
            return false;
        });
    });
</script>
@using (Html.BeginForm("Delete", "LoaiSanPhams", FormMethod.Post))
{
<h1></h1>
<div class="panel panel-default container MaginTop" >
   
    <div class="panel-heading">
        <h3 class="panel-title">Quản lý loại sản phẩm
         <div class="btn-group" role="group" aria-label="..." style="float:right">
             @Html.ActionLink("Thêm mới", "Create", "LoaiSanPham", new { @class = "btn btn-default" })
             <input type="submit" value="Xóa", class="btn btn-default popup_button_delete"/>
             @*@Html.ActionLink("Xóa", "Delete", "LoaiSanPham", new { @class = "btn btn-default" })*@
             @Html.ActionLink("Thoát", "Close", "LoaiSanPham", new { @class = "btn btn-default" })
        </div>
        </h3>
    </div>
    <div class="panel-body">
        <table class="table">
            <tr>
                <th>Chọn</th>
                <th>STT</th>
                <th>
                    @Html.DisplayNameFor(model => model.Ten)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Tieude)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Mota)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Uutien)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Hinhanh)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Tukhoa)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Thucthi)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Vitri)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Ngonngu)
                </th>
              
            </tr>
            @{ 
                var i = 1;

                foreach (var item in Model)
                {
                <tr>
                    <td>
                        <input type="checkbox" name="idLoai" id="idLoai" value="@item.IdLoai"/>
                    </td>
                    <td>@i</td>
                    <td>
                        @Html.ActionLink(item.Ten, "Edit", new { id = item.IdLoai })
                   
                        @*@Html.DisplayFor(modelItem => item.Ten)*@
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Tieude)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Mota)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Uutien)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Hinhanh)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Tukhoa)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Thucthi)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Vitri)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Ngonngu)
                    </td>
                   

                </tr>
                    i++;
                }
            }

        </table>

    </div>
  
</div>

 }