WebsiteTrangSuc/WebsiteTrangSuc/Models/Menu.cs
namespace WebsiteTrangSuc.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    [Table("Menu")]
    public partial class Menu
    {
        public int id { get; set; }

        [StringLength(50)]
        public string Ten { get; set; }

        [StringLength(50)]
        public string TieuDe { get; set; }

        [Column(TypeName = "ntext")]
        public string MoTa { get; set; }

        public int? Thutu { get; set; }

        [StringLength(50)]
        public string Trang { get; set; }

        [StringLength(50)]
        public string ThuMuc { get; set; }

        public bool? Active { get; set; }

        [StringLength(10)]
        public string LangID { get; set; }
    }
}

WebsiteTrangSuc/WebsiteTrangSuc/Areas/Administrator/Controllers/DefaultController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebsiteTrangSuc.Models;

namespace WebsiteTrangSuc.Areas.Administrator.Controllers
{
    public class DefaultController : Controller
    {
        // GET: Administrator/Default
        QLBH db = new QLBH();
        public ActionResult Index()
        {
            if(string.IsNullOrEmpty(Session["ten"].ToString()))
            {
                return RedirectToAction("Login");
            }
            else
            {
                return View();
            }
           
        }
        public PartialViewResult Menu()
        {

            return PartialView();
        }
        public ActionResult Login()
        {

            return View();
        }
        [HttpPost]
        public ActionResult Login(string txtTen, string txtMatKhau)
        {
            var ds = db.NguoiDungs.Where(s => s.Username == txtTen && s.Password == txtMatKhau).ToList();
            if(ds.Count !=0)
            {
                Session["ten"] = txtTen;
                Session["matkhau"] = txtMatKhau;
                return RedirectToAction("Index");
            }
            else
            {
                return View();
            }
        
        }
        public ActionResult Thoat()
        {
            Session["ten"] = "";
            Session["matkhau"] = "";
            return RedirectToAction("Login");
        }
    }
}

WebsiteTrangSuc/WebsiteTrangSuc/Areas/Administrator/Controllers/HangSXesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebsiteTrangSuc.Models;

namespace WebsiteTrangSuc.Areas.Administrator.Controllers
{
    public class HangSXesController : Controller
   {
        private QLBH db = new QLBH();

        // GET: Administrator/HangSXes
        public ActionResult Index()
        {
            return View(db.HangSXes.ToList());
        }

        // GET: Administrator/HangSXes/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            HangSX hangSX = db.HangSXes.Find(id);
            if (hangSX == null)
            {
                return HttpNotFound();
            }
            return View(hangSX);
        }

        // GET: Administrator/HangSXes/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Administrator/HangSXes/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Create([Bind(Include = "IdHang,Mota,Website,LienHe,UTien,ThucThi,NgonNgu")] HangSX hangSX)
        {
            if (ModelState.IsValid)
            {
                db.HangSXes.Add(hangSX);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(hangSX);
        }

        // GET: Administrator/HangSXes/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            HangSX hangSX = db.HangSXes.Find(id);
            if (hangSX == null)
            {
                return HttpNotFound();
            }
            return View(hangSX);
        }

        // POST: Administrator/HangSXes/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Edit([Bind(Include = "IdHang,Mota,Website,LienHe,UTien,ThucThi,NgonNgu")] HangSX hangSX)
        {
            if (ModelState.IsValid)
            {
                db.Entry(hangSX).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(hangSX);
        }
        [HttpPost]
        // GET: Administrator/HangSXes/Delete/5
        public ActionResult Delete(int[] idHang)
        { 
            foreach(var i in idHang)
            {
                HangSX hsx = db.HangSXes.Find(i);
                        db.HangSXes.Remove(hsx);
                        db.SaveChanges();
                }
                return RedirectToAction("Index");
            }
        //if (id == null)
        //{
        //    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //}
        //HangSX hangSX = db.HangSXes.Find(id);
        //if (hangSX == null)
        //{
        //    return HttpNotFound();
        //}
        //return View(hangSX);
        // POST: Administrator/HangSXes/Delete/5
        //[HttpPost, ActionName("Delete")]
        //[ValidateAntiForgeryToken]
        //public ActionResult DeleteConfirmed(int id)
        //{
        //    HangSX hangSX = db.HangSXes.Find(id);
        //    db.HangSXes.Remove(hangSX);
        //    db.SaveChanges();
        //    return RedirectToAction("Index");
        //}
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
        public ActionResult Close()
        {
            return RedirectToAction("Index", "Default");
        }

    }
   
 }

WebsiteTrangSuc/WebsiteTrangSuc/Areas/Administrator/Views/Default/Index.cshtml
@{
    ViewBag.Title = "Quản trị Website Trang sức Mạnh Thắng";
    Layout = "~/Areas/Administrator/Views/Shared/Admin_Layout.cshtml";
}

WebsiteTrangSuc/WebsiteTrangSuc/Areas/Administrator/Views/Default/Login.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Login</title>
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/AdminSite.css" rel="stylesheet" />
</head>
<body>
@using (Html.BeginForm("Login","Default", FormMethod.Post))
 {
    <div class="LoginLayout">
        <div class="row">
            <div class="col-md-offset-2 col-md-8" style="padding-top:30px">
                <div class="input-group">
                    <span class="input-group-btn glyphicon glyphicon-user">
                    </span>
                    @Html.TextBox("txtTen", null, new { @class = "form-control", placeholder = "Tên đăng nhập" })
                </div><!-- /input-group -->
            </div><!-- /.col-lg-6 -->
        </div>
        <div class="row">
            <div class="col-md-offset-2 col-md-8">
                <div class="input-group">
                    <span class="input-group-btn glyphicon glyphicon-lock">

                    </span>
                    @Html.Password("txtMatKhau", null, new { @class = "form-control", placeholder = "Mật khẩu" })
                </div><!-- /input-group -->
            </div><!-- /.col-lg-6 -->
        </div>
        <div class="row">
            <div class="col-md-offset-5 col-md-8">
                <div class="input-group" style="padding-top:10px">
                    <input type="submit" value="Đăng nhập" class="btn btn-primary" />
                </div><!-- /input-group -->
            </div><!-- /.col-lg-6 -->
        </div>
    </div>
  }
</body>
</html>

WebsiteTrangSuc/WebsiteTrangSuc/Areas/Administrator/Views/Default/Menu.cshtml
<nav class="navbar navbar-default">

    <div class="container-fluid">
        <div>
         @Html.ActionLink("Quản trị sản phẩm","Index","Default",new  { @class="navbar-brand"})
          
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Hệ thống <pan class="caret"></pan></a>
                    <ul class="dropdown-menu">
                        <li>
                            @Html.ActionLink("Quản lý người dùng","Index","NguoiDungs")
                        </li>
                        <li><a href="#">Sao lưu dữ liệu</a></li>
                        <li><a href="#">Quản lý Menu</a></li>
                        <li><a href="#">Quản lý Support</a></li>
                        <li><a href="#">Quản lý GroupSupport</a></li>
                        <li><a href="#">Quản lý Visitor</a></li>
                        <li role="separator" class="divider"></li>
                        <li><a href="#">Thoát</a></li>
                        <li role="separator" class="divider"></li>
                    </ul>
                </li>
            </ul>
            <ul class="nav navbar-nav">
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Quản lý sản phẩm <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li>
                            @Html.ActionLink("Danh sách sản phẩm","Index","Sanphams")
                        </li>
                        <li><a href="#">Thêm sản phẩm mới</a></li>
                        <li role="separator" class="divider"></li>
                        <li>
                            @Html.ActionLink("Danh sách loại sản phẩm","Index","LoaiSanPhams")
                        </li>
                        <li><a href="#">Thêm loại sản phẩm</a></li>
                        <li role="separator" class="divider"></li>
                        <li>
                            @Html.ActionLink("Danh sách hãng sản xuất","Index","HangSXes")
                        </li>
                        <li role="separator" class="divider"></li>
                    </ul>
                </li>
            </ul>
            <ul class="nav navbar-nav">
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Quản lý bài viết <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li>
                            @Html.ActionLink("Danh sách bài viết","Index","BaiVietHeThongs")
                        </li>
                        @*<li role="separator" class="divider"></li>*@
                        <li>
                            @Html.ActionLink("Danh sách Banner","HienthiBanner","BaiVietHeThongs")
                        </li>
                        <li><a href="#">Danh sách Quảng cáo</a></li>
                        <li><a href="#">Danh sách Media</a></li>
                        <li></li>
                        <li role="separator" class="divider"></li>
                    </ul>
                </li>
            </ul>
            <ul class="nav navbar-nav">
            <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Quản lý khách hàng<span class="caret"></span></a>
                <ul class="dropdown-menu">
                    <li><a href="#">Danh sách khách hàng</a></li>
                    <li role="separator" class="divider"></li>
                </ul>
            </li>
            </ul>
            <ul class="nav navbar-nav">
            <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Quản lý đơn hàng <span class="caret"></span></a>
                <ul class="dropdown-menu">
                    <li>
                        @Html.ActionLink("Đơn hàng - Khách hàng","Index","Donhang_Khachhang")
                    </li>
                    <li role="separator" class="divider"></li>
                    <li>
                        @Html.ActionLink("Chi tiết đơn hàng","Index","Chitietdonhangs")
                    </li>
                    <li role="separator" class="divider"></li>
                </ul>
            </li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <li><a href="#">Xin chào! @{@Session["ten"].ToString();}</a></li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        
                        <li>
                            @Html.ActionLink("Đăng xuất","Thoat","Default")
                        </li>                       
                    </ul>
                </li>
            </ul>
        </div><!-- /.navbar-collapse -->
    </div>
   <!-- /.container-fluid -->
</nav>