WebsiteTrangSuc/WebsiteTrangSuc/Models/Menu.cs
namespace WebsiteTrangSuc.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    [Table("Menu")]
    public partial class Menu
    {
        public int id { get; set; }

        [StringLength(50)]
        public string Ten { get; set; }

        [StringLength(50)]
        public string TieuDe { get; set; }

        [Column(TypeName = "ntext")]
        public string MoTa { get; set; }

        public int? Thutu { get; set; }

        [StringLength(50)]
        public string Trang { get; set; }

        [StringLength(50)]
        public string ThuMuc { get; set; }

        public bool? Active { get; set; }

        [StringLength(10)]
        public string LangID { get; set; }
    }
}

WebsiteTrangSuc/WebsiteTrangSuc/Controllers/GioHangController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebsiteTrangSuc.Models;

namespace WebsiteTrangSuc.Controllers
{
    public class GioHangController : Controller
    {
        // GET: GioHang
        const string cartname = "giohang";
        QLBH db = new QLBH();
        public ActionResult Index()
        {
            var giohang = (List<GioHang>)Session[cartname];
            return View(giohang);
        }
        public ActionResult ThemGioHang(int id)
        {
            var giohang = (List<GioHang>)Session[cartname];
            var sanpham = db.Sanphams.Find(id);
            if (giohang!=null)
            {
                if (giohang.Exists(x => x.Sanpham.id == id))
                {
                    var sp = giohang.Where(s => s.Sanpham.id == id).FirstOrDefault();
                    sp.SoLuong += sp.SoLuong;
                }
                else
                {
                    GioHang gh = new GioHang(sanpham, 1);
                    giohang.Add(gh);
                }
                Session[cartname] = giohang;
            }
            else
            {
                GioHang gh = new GioHang(sanpham, 1);
                var list = new List<GioHang>();
                list.Add(gh);
                Session[cartname] = list;
            }
            return Redirect(Request.UrlReferrer.ToString());
        }
        [HttpPost]
        public ActionResult TinhLai(int[] id, int[] soluong)
        {
            var k = 0;
            var giohang = (List<GioHang>)Session[cartname];
            foreach(int i in id)
            {
                if (giohang.Exists(s => s.Sanpham.id == i))
                {
                    var sp = giohang.Where(s => s.Sanpham.id == i).FirstOrDefault();
                    sp.SoLuong = soluong[k];
                }
                k++;
            }
            return RedirectToAction("Index");
        }
        public ActionResult ThanhToan()
        {
            if (Session["KH"] != null)
            {
                return RedirectToAction("DiaChi");
            }
            else
            {
                return View();
            }
           
        }
        [HttpPost]
        public ActionResult DangNhap(string txtTen, string txtMatKhau)
        {
            var kh = db.KhachHangs.Where(s => s.Tentruynhap == txtTen && s.Matkhau == txtMatKhau).ToList().FirstOrDefault();
            if (kh != null)
            {
                Session["KH"] = kh;
              
                return RedirectToAction("DiaChi");
            }
            else
            {
                Session["ms"] = "Đăng nhập không thành công";
                return RedirectToAction("ThanhToan");
            }
            
        }
        public ActionResult DangKy()
        {
            return View();
        }
        [HttpPost]
        public ActionResult DangKy(string txtHoTen, string txtDienThoai,string txtDiaChi,string txtTenDangNhap,string txtMatKhau)
        {
            var khachhang = db.KhachHangs.Where(s => s.Tenkhachhang == txtHoTen).ToList().FirstOrDefault();
            if (khachhang!=null)
            {
                ViewBag.ms = "Tên đăng nhập đã tồn tại";
                return View();
            }
            else
            {
                KhachHang KH = new KhachHang();
                KH.Tentruynhap = txtTenDangNhap;
                KH.Tenkhachhang = txtHoTen;
                KH.Diachi = txtDiaChi;
                KH.Dienthoai = txtDienThoai;
                KH.Matkhau = txtMatKhau;
                db.KhachHangs.Add (KH);
                db.SaveChanges();
                Session["KH"] = KH;
                return RedirectToAction("DiaChi");
            }
            
        }
        public ActionResult DiaChi()
        {
            KhachHang khachhang = new KhachHang();
            khachhang = (KhachHang)Session["KH"];
            return View(khachhang);
        }
        [HttpPost]
        public ActionResult ThemDiaChi(string Tenkhachhang,string Dienthoai,string Diachi,string txtYeuCau,string txtNgayGiaoHang)
        {
            Donhang_KhachHang dh = new Donhang_KhachHang();
            KhachHang khachhang = new KhachHang();
            khachhang = (KhachHang)Session["KH"];
            dh.Idkhachhang = khachhang.IdKhachhang;
            dh.Tennguoinhan = Tenkhachhang;
            dh.Diachinguoinhan = Diachi;
            dh.DTnguoinhan = Dienthoai;
            dh.Yeucau = txtYeuCau;
            dh.Ngaygiao = Convert.ToDateTime(txtNgayGiaoHang);
            dh.Ngaydat = DateTime.Now;
            //db.Donhang_KhachHang.Add(dh);
            //db.SaveChanges();
            Session["dathang"] = dh;
            return RedirectToAction("DatHang");
        }
        public ActionResult DatHang()
        {
           ViewBag.kh = (KhachHang)Session["KH"];
           ViewBag.gh = (List<GioHang>)Session[cartname];
           ViewBag.dh = (Donhang_KhachHang)Session["dathang"];
            return View();
        }
        [HttpPost]

        public ActionResult DatHang(string rdphuongthuctt)
        {
           KhachHang kh = (KhachHang)Session["KH"];
            List <GioHang> gh = (List<GioHang>)Session[cartname];
            Donhang_KhachHang dh = (Donhang_KhachHang)Session["dathang"];
            dh.Kieuthanhtoan = rdphuongthuctt;
            db.Donhang_KhachHang.Add(dh);
            foreach(var item in gh)
            {
                Chitietdonhang chitiet = new Chitietdonhang();
                chitiet.IdDonHang = dh.IdDonHang;
                chitiet.IdSanPham = item.Sanpham.id;
                chitiet.Soluong = item.SoLuong;
                chitiet.Dongia = item.Sanpham.GiaMoi;
                db.Chitietdonhangs.Add(chitiet);
                db.SaveChanges();
                
            }
            
            return RedirectToAction("Dathangthanhcong");
        }
        public ActionResult Dathangthanhcong()
        {
            
            return View();
        }
    }
}

WebsiteTrangSuc/WebsiteTrangSuc/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebsiteTrangSuc.Models;

namespace WebsiteTrangSuc.Controllers
{
    public class HomeController : Controller
    {
        // GET: Home
        QLBH db = new QLBH();
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult LienHe()
        {
            var lienhe = db.BaiVietHeThongs.Where(s => s.cCode == "ContactUs" && s.cLangID == "vi-VN").ToList().FirstOrDefault();
            ViewBag.lienhe = lienhe;
            return View(lienhe);
        }
        public ActionResult Gioithieu()
        {

            var gioithieu = db.BaiVietHeThongs.Where(s => s.cCode == "AboutUs" && s.cLangID == "vi-VN").ToList().FirstOrDefault();
            ViewBag.gioithieu = gioithieu;
            return View(gioithieu);
        }
        public PartialViewResult Menu()
        {

            //var ds = db.Menus.Where(s => s.Active == true && s.LangID == "vi-VN").OrderBy(s => s.Thutu).ToList();
            //ViewBag.dsmenu = ds;
            return PartialView();
        }
        public PartialViewResult Banner()
        {
            var slideshow = db.QuangCaos.Where(s => s.LangID == "vi-VN").OrderBy(s => s.AdsIndex).ToList();
            
            return PartialView(slideshow);
        }
        public PartialViewResult MenuCon()
        {
            var ds = db.Menus.Where(s => s.Active == true && s.LangID == "vi-VN").OrderBy(s => s.Thutu).ToList();
            ViewBag.dsmenu = ds;
            return PartialView();
        }
        public PartialViewResult RightMenu()
        {
            var rightmenu = db.LoaiSanPhams.Where(s => s.Thucthi == 1 && s.Ngonngu == "vi-VN").OrderBy(s => s.Vitri).ToList();
            return PartialView(rightmenu);
        }
        public PartialViewResult Footer()
        {
            var address = db.BaiVietHeThongs.Where(s => s.cCode == "Address" && s.cLangID == "vi-VN").ToList().FirstOrDefault();
            ViewBag.address = address;
            return PartialView();
          
        }
        public ActionResult DangNhap()
        {

            return View(); 
        }
        [HttpPost]
        public ActionResult DangNhap(string txtTen, string txtMatKhau)
        {
            var kh = db.KhachHangs.Where(s => s.Tentruynhap == txtTen && s.Matkhau == txtMatKhau).ToList().FirstOrDefault();
            if (kh != null)
            {
                Session["KH"] = kh;

                return RedirectToAction("Index");
            }
            else
            {
                Session["ms"] = "Đăng nhập không thành công";
                return RedirectToAction("DangNhap");
            }
        }
        public ActionResult DangKy()
        {
            return View();
        }
        [HttpPost]
        public ActionResult DangKy(string txtHoTen, string txtDienThoai, string txtDiaChi, string txtTenDangNhap, string txtMatKhau)
        {
            var khachhang = db.KhachHangs.Where(s => s.Tenkhachhang == txtHoTen).ToList().FirstOrDefault();
            if (khachhang != null)
            {
                ViewBag.ms = "Tên đăng nhập đã tồn tại";
                return View();
            }
            else
            {
                KhachHang KH = new KhachHang();
                KH.Tentruynhap = txtTenDangNhap;
                KH.Tenkhachhang = txtHoTen;
                KH.Diachi = txtDiaChi;
                KH.Dienthoai = txtDienThoai;
                KH.Matkhau = txtMatKhau;
                db.KhachHangs.Add(KH);
                db.SaveChanges();
                Session["KH"] = KH;
                return RedirectToAction("Index");
            }
        }
        public ActionResult Thoat()
        {
            Session["KH"] = null;
          
            return RedirectToAction("Index");
        }
        [HttpPost]
        public ActionResult Timkiem(string txtTimKiem) 
        {
            List<Sanpham> kqtk = db.Sanphams.Where(s => s.Tukhoa.Contains(txtTimKiem)).ToList();
            //var ds = db.Sanphams.Where(s => s.Tukhoa.Contains(txtTimKiem)).ToList();
            
            if ( kqtk.Count != 0)
            {
                return PartialView(kqtk);
            }
            else
            {
                ViewBag.thongbao = "Không tìm thấy sản phẩm cần tìm";
                return View();
            }
            
        }
        public PartialViewResult Hotnumber()
        {
            var hotnumber = db.BaiVietHeThongs.Where(s => s.cCode == "HotNumber" && s.cLangID == "vi-VN").ToList().FirstOrDefault();
            ViewBag.hotnumber = hotnumber;
            return PartialView(hotnumber);
        }
    }
    
}

WebsiteTrangSuc/WebsiteTrangSuc/Controllers/KhachHangController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebsiteTrangSuc.Models;

namespace WebsiteTrangSuc.Controllers
{
    
    public class KhachHangController : Controller
    {
        QLBH db = new QLBH();
        // GET: KhachHang
        public ActionResult Index()
        {
            return View();
        }
        [HttpGet]
        public ActionResult Thongtinkhachhang(int id)
        {
            var kh = db.KhachHangs.Where(s => s.IdKhachhang == id).ToList().FirstOrDefault();   
            return View(kh);
        }
    }
}

WebsiteTrangSuc/WebsiteTrangSuc/Controllers/SanPhamController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebsiteTrangSuc.Models;

namespace WebsiteTrangSuc.Controllers
{
    public class SanPhamController : Controller
    {
        QLBH db = new QLBH();
        // GET: SanPham
        public ActionResult Index()
        {
            return View();
        }
        public PartialViewResult SanPhamMoi()
        {
            var ds = db.Sanphams.OrderByDescending(s=>s.id).ToList().Take(3);
            return PartialView(ds);
        }
        public PartialViewResult SanPhamTieuBieu()
        {
            var ds = db.Sanphams.Where(s => s.TieuBieu == true).ToList().Take(2);
            return PartialView(ds);
        }
        [HttpGet]
        public ActionResult DanhMucSP(int id  )
        {
            var dssp = db.Sanphams.Where(s => s.IdLoai == id).OrderBy(s=>s.GiaMoi).ToList();
            ViewBag.tenloai = db.LoaiSanPhams.Where(s => s.IdLoai == id).ToList().FirstOrDefault();
            return View(dssp);
        }
        [HttpGet]
        public ActionResult Chitietsanpham(int id)
        {
            var chitiet = db.Sanphams.Where(s => s.id == id).ToList().FirstOrDefault();
            var splq = db.Sanphams.Where(s => s.IdLoai == chitiet.IdLoai && s.id != chitiet.id).ToList().Take(3);
            ViewBag.sqlq = splq;
            return View(chitiet);
        }
    }
}

WebsiteTrangSuc/WebsiteTrangSuc/Views/Home/Banner.cshtml
@model IEnumerable<WebsiteTrangSuc.Models.QuangCao>
<script src="~/Content/jquery-1.11.3.min.js"></script>
<script src="~/Content/jssor.slider-23.0.0.min.js"></script>
<script type="text/javascript">
  jQuery(document).ready(function ($) {
            var jssor_1_SlideshowTransitions = [
              {$Duration:1200,$Opacity:2}
            ];

            var jssor_1_options = {
              $AutoPlay: 1,
              $SlideshowOptions: {
                $Class: $JssorSlideshowRunner$,
                $Transitions: jssor_1_SlideshowTransitions,
                $TransitionsOrder: 1
              },
              $ArrowNavigatorOptions: {
                $Class: $JssorArrowNavigator$
              },
              $BulletNavigatorOptions: {
                $Class: $JssorBulletNavigator$
              }
            };

            var jssor_1_slider = new $JssorSlider$("jssor_1", jssor_1_options);

            /*responsive code begin*/
            /*remove responsive code if you don't want the slider scales while window resizing*/
            function ScaleSlider() {
                var refSize = jssor_1_slider.$Elmt.parentNode.clientWidth;
                if (refSize) {
                    refSize = Math.min(refSize, 800);
                    jssor_1_slider.$ScaleWidth(refSize);
                }
                else {
                    window.setTimeout(ScaleSlider, 30);
                }
            }
            ScaleSlider();
            $(window).bind("load", ScaleSlider);
            $(window).bind("resize", ScaleSlider);
            $(window).bind("orientationchange", ScaleSlider);
            /*responsive code end*/
        });
</script>
<style>
    /* jssor slider bullet navigator skin 05 css */
    /*
        .jssorb05 div           (normal)
        .jssorb05 div:hover     (normal mouseover)
        .jssorb05 .av           (active)
        .jssorb05 .av:hover     (active mouseover)
        .jssorb05 .dn           (mousedown)
        */
    .jssorb05 {
        position: absolute;
    }

        .jssorb05 div, .jssorb05 div:hover, .jssorb05 .av {
            position: absolute;
            /* size of bullet elment */
            width: 16px;
            height: 16px;
            background: url('../../Media/Image/b05.png') no-repeat;
            overflow: hidden;
            cursor: pointer;
        }

        .jssorb05 div {
            background-position: -7px -7px;
        }

            .jssorb05 div:hover, .jssorb05 .av:hover {
                background-position: -37px -7px;
            }

        .jssorb05 .av {
            background-position: -67px -7px;
        }

        .jssorb05 .dn, .jssorb05 .dn:hover {
            background-position: -97px -7px;
        }

    /* jssor slider arrow navigator skin 12 css */
    /*
        .jssora12l                  (normal)
        .jssora12r                  (normal)
        .jssora12l:hover            (normal mouseover)
        .jssora12r:hover            (normal mouseover)
        .jssora12l.jssora12ldn      (mousedown)
        .jssora12r.jssora12rdn      (mousedown)
        */
    .jssora12l, .jssora12r {
        display: block;
        position: absolute;
        /* size of arrow element */
        width: 30px;
        height: 46px;
        cursor: pointer;
        background: url('../../Media/Image/a12.png') no-repeat;
        overflow: hidden;
    }

    .jssora12l {
        background-position: -16px -37px;
    }

    .jssora12r {
        background-position: -75px -37px;
    }

    .jssora12l:hover {
        background-position: -136px -37px;
    }

    .jssora12r:hover {
        background-position: -195px -37px;
    }

    .jssora12l.jssora12ldn {
        background-position: -256px -37px;
    }

    .jssora12r.jssora12rdn {
        background-position: -315px -37px;
    }
</style>
<div id="jssor_1" style="position:relative;margin:0 auto;top:0px;left:0px;width:600px;height:300px;overflow:hidden;visibility:hidden;">
    <!-- Loading Screen -->
    <div data-u="loading" style="position:absolute;top:0px;left:0px;background-color:rgba(0,0,0,0.7);">
        <div style="filter: alpha(opacity=70); opacity: 0.7; position: absolute; display: block; top: 0px; left: 0px; width: 100%; height: 100%;"></div>
        <div style="position:absolute;display:block;background:url('../../Media/Image/loading.gif') no-repeat center center;top:0px;left:0px;width:100%;height:100%;"></div>
    </div>
    <div data-u="slides" style="cursor:default;position:relative;top:0px;left:0px;width:600px;height:300px;overflow:hidden;">
       
            @{
                foreach (var item in Model)
                {
                    <div>
                        <img data-u="image" src="@item.AdsImage" />
                    </div>

                    }
             }
        <a data-u="any" href="http://www.jssor.com" style="display:none">Simple Fade Slideshow</a>
    </div>
    <!-- Bullet Navigator -->
    <div data-u="navigator" class="jssorb05" style="bottom:16px;right:16px;" data-autocenter="1">
        <!-- bullet navigator item prototype -->
        <div data-u="prototype" style="width:16px;height:16px;"></div>
    </div>
    <!-- Arrow Navigator -->
    <span data-u="arrowleft" class="jssora12l" style="top:0px;left:0px;width:30px;height:46px;" data-autocenter="2"></span>
    <span data-u="arrowright" class="jssora12r" style="top:0px;right:0px;width:30px;height:46px;" data-autocenter="2"></span>
</div>

WebsiteTrangSuc/WebsiteTrangSuc/Views/Home/DangNhap.cshtml
@{
    ViewBag.Title = "DangNhap";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@{
    if (Session["ms"] != null)
    {
        <div class="alert alert-warning" role="alert">
            <span class="glyphicon glyphicon-exclamation-sign">
                @Session["ms"].ToString()
            </span>

        </div>
    }
}
@using (Html.BeginForm("DangNhap", "Home", FormMethod.Post))
{
    <div class="panel panel-default">
        <div class="panel-heading"><h4 style="text-align:center">Đăng nhập hệ thống</h4></div>
        <div class="panel-body">
            <div class="LoginLayout">
                <div class="row">
                    <div class="col-md-offset-2 col-md-8" style="padding-top:30px">
                        <div class="input-group">
                            <span class="input-group-btn glyphicon glyphicon-user">
                            </span>
                            @Html.TextBox("txtTen", null, new { @class = "form-control", placeholder = "Tên đăng nhập" })
                        </div><!-- /input-group -->
                    </div><!-- /.col-lg-6 -->
                </div>
                <div class="row">
                    <div class="col-md-offset-2 col-md-8">
                        <div class="input-group">
                            <span class="input-group-btn glyphicon glyphicon-lock">

                            </span>
                            @Html.Password("txtMatKhau", null, new { @class = "form-control", placeholder = "Mật khẩu" })
                        </div><!-- /input-group -->
                    </div><!-- /.col-lg-6 -->
                </div>
                <div class="row">
                    <div class="col-md-offset-5 col-md-8">
                        <div class="input-group" style="padding-top:10px">
                            <input type="submit" value="Đăng nhập" class="btn btn-primary" />
                           
                                @Html.ActionLink("Chưa có tài khoản", "DangKy", "Home")
                     

                        </div><!-- /input-group -->
                  
                    </div><!-- /.col-lg-6 -->
                </div>
            </div>
        </div>
    </div>

}

WebsiteTrangSuc/WebsiteTrangSuc/Views/Home/Footer.cshtml
@using WebsiteTrangSuc.Models;

<div class="container"><h5 style="text-align:center">
    @{
        BaiVietHeThong address = ViewBag.address;
        @Html.Raw(@address.cValue);

        
    }
                          
    </h5></div>

WebsiteTrangSuc/WebsiteTrangSuc/Views/Home/Gioithieu.cshtml
 @*@using WebsiteTrangSuc.Models
@{
    ViewBag.Title = "Gioithieu";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div class="container">
    <h5 style="text-align:center">
        @{
            BaiVietHeThong gioithieu = ViewBag.gioithieu;
            @Html.Raw(@gioithieu.cValue);
        }
    </h5>
</div>*@

WebsiteTrangSuc/WebsiteTrangSuc/Views/Home/Hotnumber.cshtml
@using WebsiteTrangSuc.Models
@{
    BaiVietHeThong hotnumber = ViewBag.hotnumber;
   @Html.Raw(@hotnumber.cValue);


}

WebsiteTrangSuc/WebsiteTrangSuc/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Index";
}
@Html.Action("Banner", "Home")
<div>
    @Html.Action("SanPhamMoi", "SanPham")
</div>

WebsiteTrangSuc/WebsiteTrangSuc/Views/Home/Menu.cshtml
@using WebsiteTrangSuc.Models

<nav class="navbar navbar-default" >
    
    <div style=" padding-right:10px; float:right" class="menucon">



        @{
            if (Session["KH"] != null)
            {
                KhachHang kh = (KhachHang)Session["KH"];
                <span class="input-group-btn glyphicon glyphicon-user" style="width:50px">
                    @Html.ActionLink(kh.Tenkhachhang, "Thongtinkhachhang", "KhachHang", new { @class = "menucon" })
                </span>
                    <span class="input-group-btn glyphicon glyphicon-remove" style="width:50px; padding-left:5px">
                        @Html.ActionLink("Đăng xuất", "Thoat", "Home", new { @class = "menucon" })
                    </span>


            }
            else
            {
                <span class="input-group-btn glyphicon glyphicon-user" style="width:50px">
                    @Html.ActionLink("Đăng nhập", "DangNhap", "Home", new { @class = "menucon" })
                </span>
                        <span class="input-group-btn glyphicon glyphicon-pencil" style="width:50px; padding-left:5px">
                            @Html.ActionLink("Đăng ký", "DangKy", "Home", new { @class = "menucon" })
                        </span>
            }
        }
    </div>

        <div style="padding-top:30px;float:right" class="menucon">
            <span class=" glyphicon glyphicon-phone-alt" >Hotnumber:
                @Html.Action("Hotnumber", "Home")
            </span>
        </div>

    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a href="@Url.Action("Index","Home")"><img src="@Url.Content("~/Media/Image/ICON3.png")" alt="Home" height="50px" width="70px" /></a>
            @*<a href="~/Views/Home/Index.cshtml">
                <img src="~/Media/Image/ICON3.png" height="50px" width="70px" />
            </a>*@
        </div>
    </div>
    @using (Html.BeginForm("TimKiem", "Home", FormMethod.Post))
    {
            <div id="searchbox" >
                <input id="txtTimKiem" name="txtTimKiem" type="text" size="15" placeholder="Nhập nội dung cần tìm kiếm...." />
                <input id="button-submit" type="submit" value="Search" />
            </div>

        //method = "get" action = "/search"
    }
    
   
</nav>

WebsiteTrangSuc/WebsiteTrangSuc/Views/Home/MenuCon.cshtml
@using WebsiteTrangSuc.Models
    <ol class="breadcrumb menucon1" data-spy="affix" data-offset-top="5">
        @{ 
            foreach(Menu item in ViewBag.dsmenu)
            {
               
                 <li>
                   <b>@Html.ActionLink(item.Ten, item.Trang, item.ThuMuc, new { @class="menucon"})</b>
                </li>
            }
        }
        <li style="float:right ; color:#ffffff" >
            <a href="@Url.Action("Index","GioHang")" class="glyphicon glyphicon-shopping-cart" aria-hidden="true" style="color:#ffffff">
                    
            </a>
                @{
                    var giohang = (List<GioHang>)Session["giohang"];
                    if (giohang != null)
                    {
                        <span class="badge">@giohang.Count</span>
                    }
                    else
                    {
                        <span class="badge">0</span>
                    }
                }
            </a>
        </li>
    </ol>

   

WebsiteTrangSuc/WebsiteTrangSuc/Views/Home/RightMenu.cshtml
@model IEnumerable<WebsiteTrangSuc.Models.LoaiSanPham>
<div class="list-group">
    <a href="#" class="list-group-item active">
        DANH MỤC SẢN PHẨM
    </a>
    @{ 
        foreach (var item in Model)
        {
            @Html.ActionLink(item.Ten,"DanhMucSP","SanPham", new {id=item.IdLoai, },new  {@class= "list-group-item" });
        }
    }
    @*<a href="#" class="list-group-item">Trang sức bạc</a>
    <a href="#" class="list-group-item">Trang sức vàng</a>
    <a href="#" class="list-group-item">Trang sức kim cương</a>
    <a href="#" class="list-group-item">Trang sức linh tinh</a>*@
</div>
<div class="list-group">
    <a href="=#" class="list-group-item active">
       SẢN PHẨM BÁN CHẠY
    </a>
    <div>
        @Html.Action("SanPhamTieuBieu","SanPham")
    </div>

    </div>

WebsiteTrangSuc/WebsiteTrangSuc/Views/Home/Timkiem.cshtml
@model IEnumerable<WebsiteTrangSuc.Models.Sanpham>
@*@using WebsiteTrangSuc.Models*@
@{
    ViewBag.Title = "Timkiem";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<ul class="nav nav-tabs" style="padding-top:10px">
    <li role="presentation" class="active" style="border-color:#428bca"><a href="#" style="background-color:#428bca;color:#ffffff">Kết quả tìm kiếm</a></li>
</ul><p></p>
@{
   
    if (ViewBag.thongbao !=null)
    {
        <div class="alert alert-warning" role="alert">
            <span class="glyphicon glyphicon-exclamation-sign">
                @ViewBag.thongbao
            </span>

        </div>
    }
    else
    {
        <div class="row">


            @{

                foreach (var item in Model)
                {
                    <div class="col-sm-6 col-md-4">
                        <div class="thumbnail">
                            <div class="hovergallery">
                                <img src="@item.HinhAnh" alt="..." height="200" width="200">
                            </div>

                            <div class="caption">
                                <h3>@item.Ten</h3>
                                <p>- Mô tả : @item.MotaNgan</p>
                                <p class="gachgia">- Giá cũ : @item.GiaCu ₫</p>
                                <h4 style="color:#ff0000">- Giá mới : @item.GiaMoi ₫</h4>
                                <p>
                                    @Html.ActionLink("Chi tiết", "Chitietsanpham", "SanPham", new { id = item.id }, new { @class = "btn btn-default", @role = "button" })
                                    @Html.ActionLink("Đặt Mua", "ThemGioHang", "GioHang", new { id = item.id }, new { @class = "btn btn-default", @role = "button" })
                                </p>
                            </div>
                        </div>
                    </div>
                }



            }

        </div>
                }
}